### PR TITLE
Update README to match the code

### PR DESCRIPTION
**Pull request by tfmorris**
Also fixes the author in the Dockerfile and provides a link to the official unofficial docker image that uses stable releases instead of the latest development snapshot.

### CODE REVIEW

**Comment by mattfullerton** [comment]
Many thanks for this. When we started dev-snapshot was necessary. Have you tested this with an e.g. PNG image?

**Comment by mattfullerton** [comment]
Many thanks for this. When we started dev-snapshot was necessary. Do you think there's actually any point in maintaining this given the alternative image available? I'm happy to have one less thing to maintain :wink:

**Comment by tfmorris** [comment]
I think it could be reasonable to point people at the other repo.  This one's top of my radar, but perhaps for historical reasons or the specific path (via Tesseract dev, I think ) that I followed.

Apologies for not having time to fully test as you asked.

**Comment by mattfullerton** [comment]
No I apologise, there's no need to test as nothing in the "code" changed

**Pull request merged**
